//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class smoothsurfingEntities : DbContext
    {
        public smoothsurfingEntities()
            : base("name=smoothsurfingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<action> action { get; set; }
        public virtual DbSet<search> search { get; set; }
        public virtual DbSet<tbActionWord> tbActionWord { get; set; }
        public virtual DbSet<tbKWord> tbKWord { get; set; }
        public virtual DbSet<volunteer> volunteer { get; set; }
    }
}
