//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class search
    {
        public int id { get; set; }
        public Nullable<int> idAction { get; set; }
        public string dit { get; set; }
    
        public virtual action action { get; set; }
    }
}
